### ISSUE TITLE
Overhaul Display of Entries in Search

### ISSUE THREAD

**Issue by PlekszyGladz** [zazuko/amos#27]
Display terms of protection for archival records. Users should always see, if a record is still protected (and for how long).

**Comment by PlekszyGladz** [comment]
24h

**Comment by l00mi** [comment]
* Signatur ricoIdentifier
* Name / Title
* scopeAndContent -> 1-2 Zeilen 
* zugang (badge/icon wenn noch nicht zugänglich) -> conditionsOfAccess
* Provenienz (aus hierarchie) -> Materialisiern
* hiddenField -> Tektonik
* tektonik -> aufklappbar mit signaturen und scopeandcontent
* date -> von / bis.. only year granularity .. 
* Thumbnail ..> Mirador

**Comment by l00mi** [comment]
![Screenshot 2021-08-17 at 15 15 19](https://user-images.githubusercontent.com/502518/129732267-fcc9844e-c176-46ae-bb7b-69d20158d633.png)

**Comment by PlekszyGladz** [comment]
New draft for the main ui as discussed in the last meeting (the display of single entries is not reflecting recent changes!): ![ui_draft](https://user-images.githubusercontent.com/5487333/142010388-94aab1b7-ba6d-44c5-a8ac-a1924b3fa5d9.png)

I created a quick HTML template of this. The whole `<head>` section and all the `<script>`s etc. are left out. Things I omitted are marked by `<...>` and the position of components is described in `<!-- TODO: ...>`-comments.  
Main changes to note: 
- completely recreated the header and footer 
- rearranged main components
- improved responsiveness of the overall layout (e.g. the max width is now limited for very wide resolutions)
- also i created some css-styles to support these changes (see below the html) 

```html
<div class="page-wrapper">
   <div class="page-header-wrapper">
      <div class="container-fluid">
         <div class="page-header">
            <div class="row align-items-center">
               <div class="logo col-6">
                  <h1>Digitaler Lesesaal</h1>
               </div>
               <div class="controlbuttons col-lg-3 order-2 order-lg-1">
                  <!-- TODO: add compact view toggle here -->
	          <...>
               </div>
               <div class="navigation col-6 col-lg-3 order-1 order-lg-2">
                  <div class="row">
                     <div class="col-12">
                        <a href="//mfk.ch/forschen/museumssammlung" title="Sammlung Museum für Kommunikation">Museum für Kommunikation</a>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-12">
                        <a href="//mfk.ch/forschen/ptt-archiv" title="PTT-Archiv">PTT-Archiv</a>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-12">
			<!-- target page of the following link will need to be created by PTT-Archiv... -->
                        <a href="/help" title="Kontakt / Hilfe">Kontakt / Hilfe</a>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <zack-search>
      <...>
      <div class="page-content-wrapper">
         <div class="container-fluid" id="contentcontainer" tabindex="-1">
            <div id="c551" class="row space-xs-top space-xs-bottom">
               <div class="col-sm-12 col-md-4">
                  <!-- TODO: put query box here -->
                  <...>
               </div>
               <div class="col-sm-12 col-md-2">
                  <!-- TODO: put result count here -->
                  <...>
               </div>
            </div>
            <div class="row justify-content-between">
               <div class="col-md-9">
                  <div class="row filter-row">
                     <div class="col-12">
                        <!-- TODO: put archive hierarchy filters here -->
                        <...>
                     </div>
                  </div>
                  <div class="row filter-row">
                     <div class="col-12">
                        <!-- TODO: put museum filters here -->
                        <...>
                     </div>
                  </div>
                  <div class="row filter-row">
                     <div class="col-12">
                        <!-- TODO: put library filters here -->
                        <...>
                     </div>
                  </div>
               </div>
               <div class="col-md-2" style="">
                  <div class="row">
                     <div class="col-12">
                        <!-- TODO: add list filter here -->
                        <...>
                     </div>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-12">
                  <!-- TODO: put histogram here -->
                  <...>
               </div>
            </div>
            <div class="row">
               <div class="col-md-12">
                  <!-- TODO: put active filters here -->
                  <...>
               </div>
            </div>
            <div id="c551" class="row space-xs-top space-sm-bottom result-row">
               <div class="col-md-12 col-sm-12">
                  <!-- TODO: put result list here -->
		  <...>
               </div>
            </div>
         </div>
      </div>
   </zack-search>
   <div class="page-footer-wrapper space-sm-top">
      <div class="container-fluid">
         <div class="page-footer row no-gutters">
            <div class="col-12">
               <div class="page-footer-navi row align-item-center">
                  <div class="col-lg-7">
                     <ul class="footernavi d-flex flex-column flex-sm-row">
                        <li class="">
                           <a href="//mfk.ch" title="Museum für Kommunikation">Museum für Kommunikation</a>
                        </li>
                        <li class="">
                           <a href="//mfk.ch/forschen/ptt-archiv" title="PTT-Archiv">PTT-Archiv</a>
                        </li>
                     </ul>
                  </div>
                  <div class="col-lg-5">
                     <ul class="footerpartner d-flex justify-content-md-start justify-content-lg-end">
                        <li>Eine Stiftung von</li>
                        <li><a href="https://www.post.ch/de" target="_blank"><img src="/icons/Logo-Post.svg" alt="sponsor logo post"></a></li>
                        <li><a href="https://www.swisscom.ch/de" target="_blank"><img src="/icons/Logo-Swisscom.svg" alt="sponsor logo swisscom"></a>
                        </li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <...>
</div>
```
CSS-styles: Some new and some overrides of existing styles. So this sheet should be loaded last. It also contains the colors for the hierarchy filters at the bottom.

```css
@media (min-width: 1400px) {
    .page-wrapper {
        width: 1400px;
        margin: auto;
    }
}

.page-header-wrapper {
    height: auto;
    margin-bottom: 20px;
}

.controlbuttons, .navigation {
    text-align: right;
    z-index: 100;
}

.zack-query-input {
    border-radius: 0px;
}

.filter-row {
    margin-top: 4px;
    margin-bottom: 4px;
}

zack-type-filters {
    justify-content: flex-start;
}

zack-filter {
    border-radius: 0px;
}

@media (min-width: 768px) {
    zack-lists {
        float: right;
    }
}

.zack-overview {
    min-height: 120px;
}

.filter-item {
    border: 1px solid black;
    border-radius: 0px;
    padding: 6px;
}

.result-row {
    height: calc(100vh - 220px);
}

.zack-content {
    height: 100%;
}

/* color schema for filters and hierarchies */
.archiv {
	background-color: #c42121;
}

.archiv-hauptabteilung, .archiv-abteilung {
	background-color: #cf433e;
}

.archiv-bestand, .archiv-teilbestand {
	background-color: #d75f5b;
}

.archiv-serie, .archiv-unterserie {
	background-color: #dd7876;
}

.archiv-dossier, .archiv-document {
	background-color: #e09191;
}

.library {
	background-color: #04a223;
}

.library-book {
	background-color: #89dd8a;
}

.museum {
	background-color: #0b26c0;
}

.museum-collection {
	background-color: #6663d4;
}

.museum-object {
	background-color: #a09ee4;
}
```
